In [9]:
import pandas as pd

In [10]:
df = pd.read_csv("df.csv")

In [11]:
print(df)

       age          workclass  fnlwgt      education  education-num  \
0       39          State-gov   77516      Bachelors             13
1       50   Self-emp-not-inc   83311      Bachelors             13
2       38            Private  215646        HS-grad              9
3       53            Private  234721           11th              7
4       28            Private  338409      Bachelors             13
5       37            Private  284582        Masters             14
6       49            Private  160187            9th              5
7       52   Self-emp-not-inc  209642        HS-grad              9
8       31            Private   45781        Masters             14
9       42            Private  159449      Bachelors             13
10      37            Private  280464   Some-college             10
11      30          State-gov  141297      Bachelors             13
12      23            Private  122272      Bachelors             13
13      32            Private  205019     Assoc-acdm             12
14      40            Private  121772      Assoc-voc             11
15      34            Private  245487        7th-8th              4
16      25   Self-emp-not-inc  176756        HS-grad              9
17      32            Private  186824        HS-grad              9
18      38            Private   28887           11th              7
19      43   Self-emp-not-inc  292175        Masters             14
20      40            Private  193524      Doctorate             16
21      54            Private  302146        HS-grad              9
22      35        Federal-gov   76845            9th              5
23      43            Private  117037           11th              7
24      59            Private  109015        HS-grad              9
25      56          Local-gov  216851      Bachelors             13
26      19            Private  168294        HS-grad              9
27      54                  ?  180211   Some-college             10
28      39            Private  367260        HS-grad              9
29      49            Private  193366        HS-grad              9
...    ...                ...     ...            ...            ...
32531   30                  ?   33811      Bachelors             13
32532   34            Private  204461      Doctorate             16
32533   54            Private  337992      Bachelors             13
32534   37            Private  179137   Some-college             10
32535   22            Private  325033           12th              8
32536   34            Private  160216      Bachelors             13
32537   30            Private  345898        HS-grad              9
32538   38            Private  139180      Bachelors             13
32539   71                  ?  287372      Doctorate             16
32540   45          State-gov  252208        HS-grad              9
32541   41                  ?  202822        HS-grad              9
32542   72                  ?  129912        HS-grad              9
32543   45          Local-gov  119199     Assoc-acdm             12
32544   31            Private  199655        Masters             14
32545   39          Local-gov  111499     Assoc-acdm             12
32546   37            Private  198216     Assoc-acdm             12
32547   43            Private  260761        HS-grad              9
32548   65   Self-emp-not-inc   99359    Prof-school             15
32549   43          State-gov  255835   Some-college             10
32550   43   Self-emp-not-inc   27242   Some-college             10
32551   32            Private   34066           10th              6
32552   43            Private   84661      Assoc-voc             11
32553   32            Private  116138        Masters             14
32554   53            Private  321865        Masters             14
32555   22            Private  310152   Some-college             10
32556   27            Private  257302     Assoc-acdm             12
32557   40            Private  154374        HS-grad              9
32558   58            Private  151910        HS-grad              9
32559   22            Private  201490        HS-grad              9
32560   52       Self-emp-inc  287927        HS-grad              9

               marital-status          occupation     relationship  \
0               Never-married        Adm-clerical    Not-in-family
1          Married-civ-spouse     Exec-managerial          Husband
2                    Divorced   Handlers-cleaners    Not-in-family
3          Married-civ-spouse   Handlers-cleaners          Husband
4          Married-civ-spouse      Prof-specialty             Wife
5          Married-civ-spouse     Exec-managerial             Wife
6       Married-spouse-absent       Other-service    Not-in-family
7          Married-civ-spouse     Exec-managerial          Husband
8               Never-married      Prof-specialty    Not-in-family
9          Married-civ-spouse     Exec-managerial          Husband
10         Married-civ-spouse     Exec-managerial          Husband
11         Married-civ-spouse      Prof-specialty          Husband
12              Never-married        Adm-clerical        Own-child
13              Never-married               Sales    Not-in-family
14         Married-civ-spouse        Craft-repair          Husband
15         Married-civ-spouse    Transport-moving          Husband
16              Never-married     Farming-fishing        Own-child
17              Never-married   Machine-op-inspct        Unmarried
18         Married-civ-spouse               Sales          Husband
19                   Divorced     Exec-managerial        Unmarried
20         Married-civ-spouse      Prof-specialty          Husband
21                  Separated       Other-service        Unmarried
22         Married-civ-spouse     Farming-fishing          Husband
23         Married-civ-spouse    Transport-moving          Husband
24                   Divorced        Tech-support        Unmarried
25         Married-civ-spouse        Tech-support          Husband
26              Never-married        Craft-repair        Own-child
27         Married-civ-spouse                   ?          Husband
28                   Divorced     Exec-managerial    Not-in-family
29         Married-civ-spouse        Craft-repair          Husband
...                       ...                 ...              ...
32531           Never-married                   ?    Not-in-family
32532      Married-civ-spouse      Prof-specialty          Husband
32533      Married-civ-spouse     Exec-managerial          Husband
32534                Divorced        Adm-clerical        Unmarried
32535           Never-married     Protective-serv        Own-child
32536           Never-married     Exec-managerial    Not-in-family
32537           Never-married        Craft-repair    Not-in-family
32538                Divorced      Prof-specialty        Unmarried
32539      Married-civ-spouse                   ?          Husband
32540               Separated        Adm-clerical        Own-child
32541               Separated                   ?    Not-in-family
32542      Married-civ-spouse                   ?          Husband
32543                Divorced      Prof-specialty        Unmarried
32544                Divorced       Other-service    Not-in-family
32545      Married-civ-spouse        Adm-clerical             Wife
32546                Divorced        Tech-support    Not-in-family
32547      Married-civ-spouse   Machine-op-inspct          Husband
32548           Never-married      Prof-specialty    Not-in-family
32549                Divorced        Adm-clerical   Other-relative
32550      Married-civ-spouse        Craft-repair          Husband
32551      Married-civ-spouse   Handlers-cleaners          Husband
32552      Married-civ-spouse               Sales          Husband
32553           Never-married        Tech-support    Not-in-family
32554      Married-civ-spouse     Exec-managerial          Husband
32555           Never-married     Protective-serv    Not-in-family
32556      Married-civ-spouse        Tech-support             Wife
32557      Married-civ-spouse   Machine-op-inspct          Husband
32558                 Widowed        Adm-clerical        Unmarried
32559           Never-married        Adm-clerical        Own-child
32560      Married-civ-spouse     Exec-managerial             Wife

                      race      sex  capital-gain  capital-loss  \
0                    White     Male          2174             0
1                    White     Male             0             0
2                    White     Male             0             0
3                    Black     Male             0             0
4                    Black   Female             0             0
5                    White   Female             0             0
6                    Black   Female             0             0
7                    White     Male             0             0
8                    White   Female         14084             0
9                    White     Male          5178             0
10                   Black     Male             0             0
11      Asian-Pac-Islander     Male             0             0
12                   White   Female             0             0
13                   Black     Male             0             0
14      Asian-Pac-Islander     Male             0             0
15      Amer-Indian-Eskimo     Male             0             0
16                   White     Male             0             0
17                   White     Male             0             0
18                   White     Male             0             0
19                   White   Female             0             0
20                   White     Male             0             0
21                   Black   Female             0             0
22                   Black     Male             0             0
23                   White     Male             0          2042
24                   White   Female             0             0
25                   White     Male             0             0
26                   White     Male             0             0
27      Asian-Pac-Islander     Male             0             0
28                   White     Male             0             0
29                   White     Male             0             0
...                    ...      ...           ...           ...
32531   Asian-Pac-Islander   Female             0             0
32532                White     Male             0             0
32533   Asian-Pac-Islander     Male             0             0
32534                White   Female             0             0
32535                Black     Male             0             0
32536                White   Female             0             0
32537                Black     Male             0             0
32538                Black   Female         15020             0
32539                White     Male             0             0
32540                White   Female             0             0
32541                Black   Female             0             0
32542                White     Male             0             0
32543                White   Female             0             0
32544                Other   Female             0             0
32545                White   Female             0             0
32546                White   Female             0             0
32547                White     Male             0             0
32548                White     Male          1086             0
32549                White   Female             0             0
32550                White     Male             0             0
32551   Amer-Indian-Eskimo     Male             0             0
32552                White     Male             0             0
32553   Asian-Pac-Islander     Male             0             0
32554                White     Male             0             0
32555                White     Male             0             0
32556                White   Female             0             0
32557                White     Male             0             0
32558                White   Female             0             0
32559                White     Male             0             0
32560                White   Female         15024             0

       hours-per-week  native-country  salary
0                  40   United-States   <=50K
1                  13   United-States   <=50K
2                  40   United-States   <=50K
3                  40   United-States   <=50K
4                  40            Cuba   <=50K
5                  40   United-States   <=50K
6                  16         Jamaica   <=50K
7                  45   United-States    >50K
8                  50   United-States    >50K
9                  40   United-States    >50K
10                 80   United-States    >50K
11                 40           India    >50K
12                 30   United-States   <=50K
13                 50   United-States   <=50K
14                 40               ?    >50K
15                 45          Mexico   <=50K
16                 35   United-States   <=50K
17                 40   United-States   <=50K
18                 50   United-States   <=50K
19                 45   United-States    >50K
20                 60   United-States    >50K
21                 20   United-States   <=50K
22                 40   United-States   <=50K
23                 40   United-States   <=50K
24                 40   United-States   <=50K
25                 40   United-States    >50K
26                 40   United-States   <=50K
27                 60           South    >50K
28                 80   United-States   <=50K
29                 40   United-States   <=50K
...               ...             ...     ...
32531              99   United-States   <=50K
32532              60   United-States    >50K
32533              50           Japan    >50K
32534              39   United-States   <=50K
32535              35   United-States   <=50K
32536              55   United-States    >50K
32537              46   United-States   <=50K
32538              45   United-States    >50K
32539              10   United-States    >50K
32540              40   United-States   <=50K
32541              32   United-States   <=50K
32542              25   United-States   <=50K
32543              48   United-States   <=50K
32544              30   United-States   <=50K
32545              20   United-States    >50K
32546              40   United-States   <=50K
32547              40          Mexico   <=50K
32548              60   United-States   <=50K
32549              40   United-States   <=50K
32550              50   United-States   <=50K
32551              40   United-States   <=50K
32552              45   United-States   <=50K
32553              11          Taiwan   <=50K
32554              40   United-States    >50K
32555              40   United-States   <=50K
32556              38   United-States   <=50K
32557              40   United-States    >50K
32558              40   United-States   <=50K
32559              20   United-States   <=50K
32560              40   United-States    >50K

[32561 rows x 15 columns]

In [12]:
df.head()

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,salary
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K

In [13]:
df.dtypes

age                int64
workclass         object
fnlwgt             int64
education         object
education-num      int64
marital-status    object
occupation        object
relationship      object
race              object
sex               object
capital-gain       int64
capital-loss       int64
hours-per-week     int64
native-country    object
salary            object
dtype: object

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32561 entries, 0 to 32560
Data columns (total 15 columns):
age               32561 non-null int64
workclass         32561 non-null object
fnlwgt            32561 non-null int64
education         32561 non-null object
education-num     32561 non-null int64
marital-status    32561 non-null object
occupation        32561 non-null object
relationship      32561 non-null object
race              32561 non-null object
sex               32561 non-null object
capital-gain      32561 non-null int64
capital-loss      32561 non-null int64
hours-per-week    32561 non-null int64
native-country    32561 non-null object
salary            32561 non-null object
dtypes: int64(6), object(9)
memory usage: 3.7+ MB

In [15]:
# Per sapere il numero di casi (righe) e il numero di variabili (column_names), si usa shape
df.shape

(32561, 15)

In [16]:
# Per impostare come indice una variabile (usandola come riferimento per l'estrazione dei dati)...
df.set_index("age")

,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,salary
age,,,,,,,,,,,,,,
39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K
37,Private,284582,Masters,14,Married-civ-spouse,Exec-managerial,Wife,White,Female,0,0,40,United-States,<=50K
49,Private,160187,9th,5,Married-spouse-absent,Other-service,Not-in-family,Black,Female,0,0,16,Jamaica,<=50K
52,Self-emp-not-inc,209642,HS-grad,9,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,45,United-States,>50K
31,Private,45781,Masters,14,Never-married,Prof-specialty,Not-in-family,White,Female,14084,0,50,United-States,>50K
42,Private,159449,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,5178,0,40,United-States,>50K
37,Private,280464,Some-college,10,Married-civ-spouse,Exec-managerial,Husband,Black,Male,0,0,80,United-States,>50K
30,State-gov,141297,Bachelors,13,Married-civ-spouse,Prof-specialty,Husband,Asian-Pac-Islander,Male,0,0,40,India,>50K
23,Private,122272,Bachelors,13,Never-married,Adm-clerical,Own-child,White,Female,0,0,30,United-States,<=50K
32,Private,205019,Assoc-acdm,12,Never-married,Sales,Not-in-family,Black,Male,0,0,50,United-States,<=50K
40,Private,121772,Assoc-voc,11,Married-civ-spouse,Craft-repair,Husband,Asian-Pac-Islander,Male,0,0,40,?,>50K
34,Private,245487,7th-8th,4,Married-civ-spouse,Transport-moving,Husband,Amer-Indian-Eskimo,Male,0,0,45,Mexico,<=50K
25,Self-emp-not-inc,176756,HS-grad,9,Never-married,Farming-fishing,Own-child,White,Male,0,0,35,United-States,<=50K
32,Private,186824,HS-grad,9,Never-married,Machine-op-inspct,Unmarried,White,Male,0,0,40,United-States,<=50K
38,Private,28887,11th,7,Married-civ-spouse,Sales,Husband,White,Male,0,0,50,United-States,<=50K
43,Self-emp-not-inc,292175,Masters,14,Divorced,Exec-managerial,Unmarried,White,Female,0,0,45,United-States,>50K
40,Private,193524,Doctorate,16,Married-civ-spouse,Prof-specialty,Husband,White,Male,0,0,60,United-States,>50K
54,Private,302146,HS-grad,9,Separated,Other-service,Unmarried,Black,Female,0,0,20,United-States,<=50K
35,Federal-gov,76845,9th,5,Married-civ-spouse,Farming-fishing,Husband,Black,Male,0,0,40,United-States,<=50K
43,Private,117037,11th,7,Married-civ-spouse,Transport-moving,Husband,White,Male,0,2042,40,United-States,<=50K
59,Private,109015,HS-grad,9,Divorced,Tech-support,Unmarried,White,Female,0,0,40,United-States,<=50K
56,Local-gov,216851,Bachelors,13,Married-civ-spouse,Tech-support,Husband,White,Male,0,0,40,United-States,>50K
19,Private,168294,HS-grad,9,Never-married,Craft-repair,Own-child,White,Male,0,0,40,United-States,<=50K
54,?,180211,Some-college,10,Married-civ-spouse,?,Husband,Asian-Pac-Islander,Male,0,0,60,South,>50K
39,Private,367260,HS-grad,9,Divorced,Exec-managerial,Not-in-family,White,Male,0,0,80,United-States,<=50K
49,Private,193366,HS-grad,9,Married-civ-spouse,Craft-repair,Husband,White,Male,0,0,40,United-States,<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30,?,33811,Bachelors,13,Never-married,?,Not-in-family,Asian-Pac-Islander,Female,0,0,99,United-States,<=50K
34,Private,204461,Doctorate,16,Married-civ-spouse,Prof-specialty,Husband,White,Male,0,0,60,United-States,>50K
54,Private,337992,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,Asian-Pac-Islander,Male,0,0,50,Japan,>50K
37,Private,179137,Some-college,10,Divorced,Adm-clerical,Unmarried,White,Female,0,0,39,United-States,<=50K
22,Private,325033,12th,8,Never-married,Protective-serv,Own-child,Black,Male,0,0,35,United-States,<=50K
34,Private,160216,Bachelors,13,Never-married,Exec-managerial,Not-in-family,White,Female,0,0,55,United-States,>50K
30,Private,345898,HS-grad,9,Never-married,Craft-repair,Not-in-family,Black,Male,0,0,46,United-States,<=50K
38,Private,139180,Bachelors,13,Divorced,Prof-specialty,Unmarried,Black,Female,15020,0,45,United-States,>50K
71,?,287372,Doctorate,16,Married-civ-spouse,?,Husband,White,Male,0,0,10,United-States,>50K
45,State-gov,252208,HS-grad,9,Separated,Adm-clerical,Own-child,White,Female,0,0,40,United-States,<=50K
41,?,202822,HS-grad,9,Separated,?,Not-in-family,Black,Female,0,0,32,United-States,<=50K
72,?,129912,HS-grad,9,Married-civ-spouse,?,Husband,White,Male,0,0,25,United-States,<=50K
45,Local-gov,119199,Assoc-acdm,12,Divorced,Prof-specialty,Unmarried,White,Female,0,0,48,United-States,<=50K
31,Private,199655,Masters,14,Divorced,Other-service,Not-in-family,Other,Female,0,0,30,United-States,<=50K
39,Local-gov,111499,Assoc-acdm,12,Married-civ-spouse,Adm-clerical,Wife,White,Female,0,0,20,United-States,>50K
37,Private,198216,Assoc-acdm,12,Divorced,Tech-support,Not-in-family,White,Female,0,0,40,United-States,<=50K
43,Private,260761,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,40,Mexico,<=50K
65,Self-emp-not-inc,99359,Prof-school,15,Never-married,Prof-specialty,Not-in-family,White,Male,1086,0,60,United-States,<=50K
43,State-gov,255835,Some-college,10,Divorced,Adm-clerical,Other-relative,White,Female,0,0,40,United-States,<=50K
43,Self-emp-not-inc,27242,Some-college,10,Married-civ-spouse,Craft-repair,Husband,White,Male,0,0,50,United-States,<=50K
32,Private,34066,10th,6,Married-civ-spouse,Handlers-cleaners,Husband,Amer-Indian-Eskimo,Male,0,0,40,United-States,<=50K
43,Private,84661,Assoc-voc,11,Married-civ-spouse,Sales,Husband,White,Male,0,0,45,United-States,<=50K
32,Private,116138,Masters,14,Never-married,Tech-support,Not-in-family,Asian-Pac-Islander,Male,0,0,11,Taiwan,<=50K
53,Private,321865,Masters,14,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,40,United-States,>50K
22,Private,310152,Some-college,10,Never-married,Protective-serv,Not-in-family,White,Male,0,0,40,United-States,<=50K
27,Private,257302,Assoc-acdm,12,Married-civ-spouse,Tech-support,Wife,White,Female,0,0,38,United-States,<=50K
40,Private,154374,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,40,United-States,>50K
58,Private,151910,HS-grad,9,Widowed,Adm-clerical,Unmarried,White,Female,0,0,40,United-States,<=50K
22,Private,201490,HS-grad,9,Never-married,Adm-clerical,Own-child,White,Male,0,0,20,United-States,<=50K
52,Self-emp-inc,287927,HS-grad,9,Married-civ-spouse,Exec-managerial,Wife,White,Female,15024,0,40,United-States,>50K

In [18]:
# Per ordinare i dati secondo una delle colonne, uso sort_values
df.sort_values(by= 'hours-per-week', ascending=False)

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,salary
8654,30,Private,103596,HS-grad,9,Never-married,Protective-serv,Not-in-family,White,Male,0,0,99,United-States,<=50K
15460,37,Private,241174,Bachelors,13,Married-civ-spouse,Prof-specialty,Husband,White,Male,0,0,99,United-States,>50K
935,37,Private,176900,HS-grad,9,Married-civ-spouse,Craft-repair,Husband,White,Male,0,0,99,United-States,>50K
26250,36,Self-emp-not-inc,257250,Assoc-voc,11,Married-civ-spouse,Farming-fishing,Husband,White,Male,0,0,99,United-States,<=50K
16992,19,Private,121074,7th-8th,4,Married-civ-spouse,Craft-repair,Husband,White,Male,0,0,99,United-States,<=50K
25831,31,Private,147284,Doctorate,16,Married-civ-spouse,Prof-specialty,Husband,White,Male,0,1977,99,United-States,>50K
12625,51,Private,160724,Doctorate,16,Married-civ-spouse,Prof-specialty,Husband,Asian-Pac-Islander,Male,0,0,99,South,<=50K
26858,66,Private,262285,Bachelors,13,Married-civ-spouse,Prof-specialty,Husband,White,Male,0,0,99,United-States,<=50K
5432,44,Private,83508,Prof-school,15,Divorced,Prof-specialty,Not-in-family,White,Female,2354,0,99,United-States,<=50K
4441,43,Self-emp-inc,286750,Prof-school,15,Married-civ-spouse,Prof-specialty,Husband,Black,Male,0,0,99,United-States,>50K
4086,50,?,174964,10th,6,Married-civ-spouse,?,Husband,White,Male,0,0,99,United-States,<=50K
15016,62,Private,272209,HS-grad,9,Divorced,Priv-house-serv,Unmarried,Black,Female,0,0,99,United-States,<=50K
22557,55,Self-emp-not-inc,95149,Some-college,10,Married-civ-spouse,Transport-moving,Husband,White,Male,0,0,99,United-States,<=50K
9831,67,Private,35015,Masters,14,Never-married,Prof-specialty,Not-in-family,White,Male,0,0,99,United-States,<=50K
10468,44,Self-emp-not-inc,277783,Masters,14,Never-married,Farming-fishing,Own-child,White,Male,0,0,99,United-States,<=50K
25806,49,?,31478,7th-8th,4,Married-civ-spouse,?,Husband,White,Male,0,0,99,United-States,<=50K
18603,33,Self-emp-not-inc,67482,Assoc-voc,11,Divorced,Other-service,Unmarried,White,Female,0,0,99,United-States,<=50K
22720,39,Private,237713,Prof-school,15,Married-civ-spouse,Sales,Husband,White,Male,0,2415,99,United-States,>50K
19399,39,Self-emp-inc,163057,Some-college,10,Divorced,Craft-repair,Not-in-family,White,Male,0,0,99,United-States,<=50K
21056,64,Local-gov,142166,HS-grad,9,Married-civ-spouse,Craft-repair,Husband,White,Male,0,0,99,United-States,<=50K
6898,53,Self-emp-not-inc,151159,10th,6,Married-spouse-absent,Transport-moving,Not-in-family,White,Male,0,0,99,United-States,<=50K
20036,61,Self-emp-inc,102191,Masters,14,Widowed,Exec-managerial,Unmarried,White,Female,0,0,99,United-States,<=50K
18881,43,Private,249771,HS-grad,9,Married-civ-spouse,Transport-moving,Husband,Asian-Pac-Islander,Male,0,0,99,United-States,<=50K
13558,38,Private,191103,Prof-school,15,Married-civ-spouse,Prof-specialty,Husband,White,Male,0,0,99,United-States,>50K
22313,26,Self-emp-not-inc,258306,10th,6,Married-civ-spouse,Farming-fishing,Husband,White,Male,0,0,99,United-States,<=50K
23398,66,Private,28367,Bachelors,13,Married-civ-spouse,Priv-house-serv,Other-relative,White,Male,0,0,99,United-States,<=50K
30992,40,Self-emp-inc,104235,Masters,14,Never-married,Other-service,Own-child,White,Male,0,0,99,United-States,<=50K
30036,40,Private,25005,Bachelors,13,Married-civ-spouse,Prof-specialty,Husband,White,Male,15024,0,99,United-States,>50K
12788,24,State-gov,208826,Doctorate,16,Never-married,Prof-specialty,Not-in-family,White,Female,0,0,99,England,<=50K
31699,43,Self-emp-not-inc,163108,Some-college,10,Married-civ-spouse,Farming-fishing,Husband,White,Male,0,0,99,United-States,<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13026,79,?,100881,Assoc-acdm,12,Married-civ-spouse,?,Wife,White,Female,0,0,2,United-States,>50K
29097,68,?,141181,9th,5,Married-civ-spouse,?,Husband,White,Male,0,0,2,United-States,<=50K
29867,47,Private,158451,Masters,14,Married-civ-spouse,Prof-specialty,Wife,White,Female,0,0,2,United-States,>50K
1458,76,?,211453,HS-grad,9,Widowed,?,Not-in-family,Black,Female,0,0,2,United-States,<=50K
30002,18,Private,279593,11th,7,Never-married,Prof-specialty,Own-child,White,Female,0,0,2,United-States,<=50K
19353,67,Self-emp-not-inc,148690,Masters,14,Widowed,Prof-specialty,Not-in-family,White,Male,18481,0,2,United-States,>50K
14645,32,Private,402089,Bachelors,13,Married-civ-spouse,Adm-clerical,Wife,White,Female,0,0,2,United-States,<=50K
19427,24,Local-gov,176178,Assoc-acdm,12,Never-married,Prof-specialty,Own-child,White,Female,0,0,2,United-States,<=50K
3291,74,?,29866,7th-8th,4,Married-civ-spouse,?,Husband,White,Male,0,0,2,United-States,<=50K
17634,40,Self-emp-not-inc,198953,Assoc-acdm,12,Never-married,Prof-specialty,Own-child,Black,Female,0,0,2,United-States,<=50K
24284,57,Self-emp-not-inc,56480,HS-grad,9,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,1,United-States,<=50K
189,58,State-gov,109567,Doctorate,16,Married-civ-spouse,Prof-specialty,Husband,White,Male,0,0,1,United-States,>50K
23536,69,?,320280,Some-college,10,Never-married,?,Not-in-family,White,Male,1848,0,1,United-States,<=50K
5766,62,?,97231,Some-college,10,Married-civ-spouse,?,Wife,White,Female,0,0,1,United-States,<=50K
20909,77,Self-emp-not-inc,71676,Some-college,10,Widowed,Adm-clerical,Not-in-family,White,Female,0,1944,1,United-States,<=50K
5808,76,?,211574,10th,6,Married-civ-spouse,?,Husband,White,Male,0,0,1,United-States,<=50K
1036,66,Self-emp-inc,150726,9th,5,Married-civ-spouse,Exec-managerial,Husband,White,Male,1409,0,1,?,<=50K
20072,65,?,76043,HS-grad,9,Married-civ-spouse,?,Husband,White,Male,0,0,1,United-States,>50K
25078,74,Private,260669,10th,6,Divorced,Other-service,Not-in-family,White,Female,0,0,1,United-States,<=50K
8447,67,?,244122,Assoc-voc,11,Widowed,?,Not-in-family,White,Female,0,0,1,United-States,<=50K
1262,69,?,195779,Assoc-voc,11,Widowed,?,Not-in-family,White,Female,0,0,1,United-States,<=50K
19337,72,?,76860,HS-grad,9,Married-civ-spouse,?,Husband,Asian-Pac-Islander,Male,0,0,1,United-States,<=50K
11451,27,Private,147951,HS-grad,9,Never-married,Machine-op-inspct,Other-relative,White,Male,0,0,1,United-States,<=50K
19750,23,Private,72887,HS-grad,9,Never-married,Craft-repair,Own-child,Asian-Pac-Islander,Male,0,0,1,Vietnam,<=50K
5632,45,?,189564,Masters,14,Married-civ-spouse,?,Wife,White,Female,0,0,1,United-States,<=50K
22960,21,Private,184135,HS-grad,9,Never-married,Machine-op-inspct,Own-child,Black,Male,0,0,1,United-States,<=50K
9147,75,?,260543,10th,6,Widowed,?,Other-relative,Asian-Pac-Islander,Female,0,0,1,China,<=50K
29752,69,?,117525,Assoc-acdm,12,Divorced,?,Unmarried,White,Female,0,0,1,United-States,<=50K
5590,78,?,363134,HS-grad,9,Widowed,?,Not-in-family,White,Female,0,0,1,United-States,<=50K
32525,81,?,120478,Assoc-voc,11,Divorced,?,Unmarried,White,Female,0,0,1,?,<=50K

In [20]:
# E' possibile ordinare anche i dati in ordine alfabetico
df.sort_values(by= 'native-country', ascending=True)

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,salary
21541,27,Private,169958,5th-6th,3,Never-married,Craft-repair,Own-child,White,Male,0,0,40,?,<=50K
18277,90,Private,311184,Bachelors,13,Married-civ-spouse,Sales,Husband,White,Male,0,0,20,?,<=50K
27305,34,Self-emp-not-inc,114185,Bachelors,13,Divorced,Transport-moving,Not-in-family,White,Male,0,0,50,?,<=50K
5854,40,Private,37618,Some-college,10,Married-civ-spouse,Craft-repair,Husband,White,Male,0,0,40,?,<=50K
27299,37,Self-emp-not-inc,327164,Some-college,10,Married-civ-spouse,Craft-repair,Husband,White,Male,0,0,70,?,<=50K
32169,25,Private,149943,HS-grad,9,Never-married,Other-service,Other-relative,Asian-Pac-Islander,Male,4101,0,60,?,<=50K
21382,62,Local-gov,41793,Masters,14,Separated,Prof-specialty,Not-in-family,White,Female,0,0,50,?,<=50K
21393,37,Self-emp-not-inc,187411,Bachelors,13,Married-civ-spouse,Transport-moving,Husband,White,Male,0,0,50,?,<=50K
17452,47,Self-emp-inc,119471,7th-8th,4,Never-married,Craft-repair,Not-in-family,Other,Male,0,0,40,?,<=50K
12362,29,State-gov,106334,Masters,14,Never-married,Exec-managerial,Not-in-family,White,Male,0,0,40,?,<=50K
10403,28,Private,150025,11th,7,Never-married,Craft-repair,Not-in-family,White,Male,0,0,40,?,<=50K
10408,39,Private,137522,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,Asian-Pac-Islander,Male,0,0,40,?,>50K
18233,45,Private,129387,Assoc-acdm,12,Divorced,Tech-support,Unmarried,White,Female,0,0,40,?,<=50K
12329,22,Private,112164,Some-college,10,Never-married,Exec-managerial,Own-child,White,Female,0,0,40,?,<=50K
15931,22,Private,253799,Bachelors,13,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,45,?,<=50K
15932,52,Private,266138,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,40,?,>50K
12315,52,Private,201310,Bachelors,13,Divorced,Exec-managerial,Not-in-family,White,Male,0,0,40,?,<=50K
5963,36,Private,189674,HS-grad,9,Never-married,Priv-house-serv,Unmarried,Black,Female,0,0,28,?,<=50K
453,42,Private,197583,Assoc-acdm,12,Married-civ-spouse,Exec-managerial,Husband,Black,Male,0,0,40,?,>50K
23236,54,Self-emp-inc,304570,Bachelors,13,Married-civ-spouse,Machine-op-inspct,Husband,Asian-Pac-Islander,Male,7688,0,40,?,>50K
24980,37,Private,154571,Some-college,10,Married-civ-spouse,Craft-repair,Husband,Asian-Pac-Islander,Male,0,0,40,?,<=50K
23284,20,Private,153583,Some-college,10,Never-married,Adm-clerical,Own-child,White,Female,0,0,40,?,<=50K
1593,55,Private,98361,Masters,14,Married-civ-spouse,Prof-specialty,Husband,White,Male,15024,0,50,?,>50K
5709,37,Federal-gov,129573,Doctorate,16,Married-civ-spouse,Prof-specialty,Husband,White,Male,0,0,72,?,>50K
31128,56,Local-gov,268213,Masters,14,Married-civ-spouse,Prof-specialty,Husband,White,Male,0,0,35,?,>50K
8477,24,Private,178255,Some-college,10,Married-civ-spouse,Priv-house-serv,Wife,White,Female,0,0,40,?,<=50K
1581,31,Private,169104,Bachelors,13,Never-married,Sales,Own-child,Asian-Pac-Islander,Male,0,0,40,?,<=50K
27383,32,Self-emp-not-inc,261056,Bachelors,13,Never-married,Prof-specialty,Own-child,Black,Female,2174,0,60,?,<=50K
5841,50,Private,196193,Masters,14,Married-spouse-absent,Prof-specialty,Other-relative,White,Male,0,0,60,?,<=50K
10343,39,Self-emp-not-inc,331481,Bachelors,13,Divorced,Craft-repair,Not-in-family,Black,Male,0,1669,60,?,<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2653,19,Private,115248,Some-college,10,Never-married,Adm-clerical,Not-in-family,Asian-Pac-Islander,Male,0,0,40,Vietnam,<=50K
4826,20,Private,147171,Some-college,10,Never-married,Adm-clerical,Unmarried,Asian-Pac-Islander,Female,0,0,40,Vietnam,<=50K
14507,23,Private,256211,Some-college,10,Never-married,Adm-clerical,Not-in-family,Asian-Pac-Islander,Male,0,0,24,Vietnam,<=50K
2259,38,Local-gov,123983,Bachelors,13,Never-married,Exec-managerial,Unmarried,Asian-Pac-Islander,Male,0,1741,40,Vietnam,<=50K
19511,30,Private,190912,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Asian-Pac-Islander,Male,0,1651,40,Vietnam,<=50K
15124,45,Private,101656,10th,6,Never-married,Machine-op-inspct,Not-in-family,Asian-Pac-Islander,Male,0,0,40,Vietnam,<=50K
28773,21,?,123983,Some-college,10,Never-married,?,Other-relative,Asian-Pac-Islander,Male,0,0,10,Vietnam,<=50K
31079,26,Private,122575,Bachelors,13,Never-married,Exec-managerial,Unmarried,Asian-Pac-Islander,Male,0,0,60,Vietnam,<=50K
17269,73,Self-emp-not-inc,233882,HS-grad,9,Married-civ-spouse,Farming-fishing,Husband,Asian-Pac-Islander,Male,0,2457,40,Vietnam,<=50K
4168,23,Private,125491,Some-college,10,Never-married,Other-service,Not-in-family,Asian-Pac-Islander,Female,0,0,35,Vietnam,<=50K
3832,24,Private,123983,11th,7,Married-civ-spouse,Transport-moving,Husband,Asian-Pac-Islander,Male,0,0,40,Vietnam,<=50K
26878,25,Private,139012,Bachelors,13,Never-married,Sales,Own-child,Asian-Pac-Islander,Male,2174,0,40,Vietnam,<=50K
18031,44,Private,172475,HS-grad,9,Divorced,Adm-clerical,Not-in-family,Asian-Pac-Islander,Female,0,0,40,Vietnam,<=50K
13821,30,Private,176123,10th,6,Never-married,Machine-op-inspct,Other-relative,Asian-Pac-Islander,Male,0,0,40,Vietnam,<=50K
6328,20,Private,175069,Some-college,10,Never-married,Adm-clerical,Own-child,White,Male,0,0,40,Yugoslavia,<=50K
22200,56,Private,155657,7th-8th,4,Divorced,Machine-op-inspct,Not-in-family,White,Female,0,0,20,Yugoslavia,<=50K
26614,36,Self-emp-inc,337778,Some-college,10,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,60,Yugoslavia,>50K
30543,22,Private,180060,HS-grad,9,Never-married,Exec-managerial,Not-in-family,White,Male,0,0,40,Yugoslavia,<=50K
13125,66,Private,142624,Assoc-acdm,12,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,5556,0,40,Yugoslavia,>50K
20549,35,Private,81280,Bachelors,13,Married-civ-spouse,Farming-fishing,Husband,White,Male,0,0,65,Yugoslavia,>50K
12506,40,Local-gov,183096,9th,5,Married-civ-spouse,Other-service,Wife,White,Female,0,0,40,Yugoslavia,>50K
29437,43,Private,557349,10th,6,Married-civ-spouse,Transport-moving,Husband,White,Male,0,0,40,Yugoslavia,<=50K
1025,56,Private,169133,HS-grad,9,Married-civ-spouse,Other-service,Husband,White,Male,0,0,50,Yugoslavia,<=50K
28487,45,Private,192323,Assoc-acdm,12,Married-civ-spouse,Craft-repair,Husband,White,Male,0,0,66,Yugoslavia,<=50K
12816,31,Private,182177,Bachelors,13,Married-civ-spouse,Other-service,Husband,White,Male,0,0,40,Yugoslavia,<=50K
23814,41,Self-emp-not-inc,145441,Assoc-voc,11,Married-civ-spouse,Craft-repair,Husband,White,Male,0,0,40,Yugoslavia,<=50K
7287,35,Private,164526,HS-grad,9,Married-civ-spouse,Other-service,Husband,White,Male,0,0,40,Yugoslavia,>50K
31519,29,Private,273051,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,52,Yugoslavia,>50K
4447,25,Private,191230,Some-college,10,Never-married,Exec-managerial,Own-child,White,Female,0,0,40,Yugoslavia,<=50K
18247,41,Private,324629,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,40,Yugoslavia,<=50K

In [22]:
# Per effettuare lo slicing sui dati
df[:100]

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,salary
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K
5,37,Private,284582,Masters,14,Married-civ-spouse,Exec-managerial,Wife,White,Female,0,0,40,United-States,<=50K
6,49,Private,160187,9th,5,Married-spouse-absent,Other-service,Not-in-family,Black,Female,0,0,16,Jamaica,<=50K
7,52,Self-emp-not-inc,209642,HS-grad,9,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,45,United-States,>50K
8,31,Private,45781,Masters,14,Never-married,Prof-specialty,Not-in-family,White,Female,14084,0,50,United-States,>50K
9,42,Private,159449,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,5178,0,40,United-States,>50K
10,37,Private,280464,Some-college,10,Married-civ-spouse,Exec-managerial,Husband,Black,Male,0,0,80,United-States,>50K
11,30,State-gov,141297,Bachelors,13,Married-civ-spouse,Prof-specialty,Husband,Asian-Pac-Islander,Male,0,0,40,India,>50K
12,23,Private,122272,Bachelors,13,Never-married,Adm-clerical,Own-child,White,Female,0,0,30,United-States,<=50K
13,32,Private,205019,Assoc-acdm,12,Never-married,Sales,Not-in-family,Black,Male,0,0,50,United-States,<=50K
14,40,Private,121772,Assoc-voc,11,Married-civ-spouse,Craft-repair,Husband,Asian-Pac-Islander,Male,0,0,40,?,>50K
15,34,Private,245487,7th-8th,4,Married-civ-spouse,Transport-moving,Husband,Amer-Indian-Eskimo,Male,0,0,45,Mexico,<=50K
16,25,Self-emp-not-inc,176756,HS-grad,9,Never-married,Farming-fishing,Own-child,White,Male,0,0,35,United-States,<=50K
17,32,Private,186824,HS-grad,9,Never-married,Machine-op-inspct,Unmarried,White,Male,0,0,40,United-States,<=50K
18,38,Private,28887,11th,7,Married-civ-spouse,Sales,Husband,White,Male,0,0,50,United-States,<=50K
19,43,Self-emp-not-inc,292175,Masters,14,Divorced,Exec-managerial,Unmarried,White,Female,0,0,45,United-States,>50K
20,40,Private,193524,Doctorate,16,Married-civ-spouse,Prof-specialty,Husband,White,Male,0,0,60,United-States,>50K
21,54,Private,302146,HS-grad,9,Separated,Other-service,Unmarried,Black,Female,0,0,20,United-States,<=50K
22,35,Federal-gov,76845,9th,5,Married-civ-spouse,Farming-fishing,Husband,Black,Male,0,0,40,United-States,<=50K
23,43,Private,117037,11th,7,Married-civ-spouse,Transport-moving,Husband,White,Male,0,2042,40,United-States,<=50K
24,59,Private,109015,HS-grad,9,Divorced,Tech-support,Unmarried,White,Female,0,0,40,United-States,<=50K
25,56,Local-gov,216851,Bachelors,13,Married-civ-spouse,Tech-support,Husband,White,Male,0,0,40,United-States,>50K
26,19,Private,168294,HS-grad,9,Never-married,Craft-repair,Own-child,White,Male,0,0,40,United-States,<=50K
27,54,?,180211,Some-college,10,Married-civ-spouse,?,Husband,Asian-Pac-Islander,Male,0,0,60,South,>50K
28,39,Private,367260,HS-grad,9,Divorced,Exec-managerial,Not-in-family,White,Male,0,0,80,United-States,<=50K
29,49,Private,193366,HS-grad,9,Married-civ-spouse,Craft-repair,Husband,White,Male,0,0,40,United-States,<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
70,19,Private,101509,Some-college,10,Never-married,Prof-specialty,Own-child,White,Male,0,0,32,United-States,<=50K
71,31,Private,309974,Bachelors,13,Separated,Sales,Own-child,Black,Female,0,0,40,United-States,<=50K
72,29,Self-emp-not-inc,162298,Bachelors,13,Married-civ-spouse,Sales,Husband,White,Male,0,0,70,United-States,>50K
73,23,Private,211678,Some-college,10,Never-married,Machine-op-inspct,Not-in-family,White,Male,0,0,40,United-States,<=50K
74,79,Private,124744,Some-college,10,Married-civ-spouse,Prof-specialty,Other-relative,White,Male,0,0,20,United-States,<=50K
75,27,Private,213921,HS-grad,9,Never-married,Other-service,Own-child,White,Male,0,0,40,Mexico,<=50K
76,40,Private,32214,Assoc-acdm,12,Married-civ-spouse,Adm-clerical,Husband,White,Male,0,0,40,United-States,<=50K
77,67,?,212759,10th,6,Married-civ-spouse,?,Husband,White,Male,0,0,2,United-States,<=50K
78,18,Private,309634,11th,7,Never-married,Other-service,Own-child,White,Female,0,0,22,United-States,<=50K
79,31,Local-gov,125927,7th-8th,4,Married-civ-spouse,Farming-fishing,Husband,White,Male,0,0,40,United-States,<=50K
80,18,Private,446839,HS-grad,9,Never-married,Sales,Not-in-family,White,Male,0,0,30,United-States,<=50K
81,52,Private,276515,Bachelors,13,Married-civ-spouse,Other-service,Husband,White,Male,0,0,40,Cuba,<=50K
82,46,Private,51618,HS-grad,9,Married-civ-spouse,Other-service,Wife,White,Female,0,0,40,United-States,<=50K
83,59,Private,159937,HS-grad,9,Married-civ-spouse,Sales,Husband,White,Male,0,0,48,United-States,<=50K
84,44,Private,343591,HS-grad,9,Divorced,Craft-repair,Not-in-family,White,Female,14344,0,40,United-States,>50K
85,53,Private,346253,HS-grad,9,Divorced,Sales,Own-child,White,Female,0,0,35,United-States,<=50K
86,49,Local-gov,268234,HS-grad,9,Married-civ-spouse,Protective-serv,Husband,White,Male,0,0,40,United-States,>50K
87,33,Private,202051,Masters,14,Married-civ-spouse,Prof-specialty,Husband,White,Male,0,0,50,United-States,<=50K
88,30,Private,54334,9th,5,Never-married,Sales,Not-in-family,White,Male,0,0,40,United-States,<=50K
89,43,Federal-gov,410867,Doctorate,16,Never-married,Prof-specialty,Not-in-family,White,Female,0,0,50,United-States,>50K
90,57,Private,249977,Assoc-voc,11,Married-civ-spouse,Prof-specialty,Husband,White,Male,0,0,40,United-States,<=50K
91,37,Private,286730,Some-college,10,Divorced,Craft-repair,Unmarried,White,Female,0,0,40,United-States,<=50K
92,28,Private,212563,Some-college,10,Divorced,Machine-op-inspct,Unmarried,Black,Female,0,0,25,United-States,<=50K
93,30,Private,117747,HS-grad,9,Married-civ-spouse,Sales,Wife,Asian-Pac-Islander,Female,0,1573,35,?,<=50K
94,34,Local-gov,226296,Bachelors,13,Married-civ-spouse,Protective-serv,Husband,White,Male,0,0,40,United-States,>50K
95,29,Local-gov,115585,Some-college,10,Never-married,Handlers-cleaners,Not-in-family,White,Male,0,0,50,United-States,<=50K
96,48,Self-emp-not-inc,191277,Doctorate,16,Married-civ-spouse,Prof-specialty,Husband,White,Male,0,1902,60,United-States,>50K
97,37,Private,202683,Some-college,10,Married-civ-spouse,Sales,Husband,White,Male,0,0,48,United-States,>50K
98,48,Private,171095,Assoc-acdm,12,Divorced,Exec-managerial,Unmarried,White,Female,0,0,40,England,<=50K
99,32,Federal-gov,249409,HS-grad,9,Never-married,Other-service,Own-child,Black,Male,0,0,40,United-States,<=50K

In [25]:
# Per estrarre dei dati secondo alcune condizioni
df[df["age"] > 50]

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,salary
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
7,52,Self-emp-not-inc,209642,HS-grad,9,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,45,United-States,>50K
21,54,Private,302146,HS-grad,9,Separated,Other-service,Unmarried,Black,Female,0,0,20,United-States,<=50K
24,59,Private,109015,HS-grad,9,Divorced,Tech-support,Unmarried,White,Female,0,0,40,United-States,<=50K
25,56,Local-gov,216851,Bachelors,13,Married-civ-spouse,Tech-support,Husband,White,Male,0,0,40,United-States,>50K
27,54,?,180211,Some-college,10,Married-civ-spouse,?,Husband,Asian-Pac-Islander,Male,0,0,60,South,>50K
41,53,Self-emp-not-inc,88506,Bachelors,13,Married-civ-spouse,Prof-specialty,Husband,White,Male,0,0,40,United-States,<=50K
45,57,Federal-gov,337895,Bachelors,13,Married-civ-spouse,Prof-specialty,Husband,Black,Male,0,0,40,United-States,>50K
46,53,Private,144361,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,38,United-States,<=50K
67,53,Private,169846,HS-grad,9,Married-civ-spouse,Adm-clerical,Wife,White,Female,0,0,40,United-States,>50K
74,79,Private,124744,Some-college,10,Married-civ-spouse,Prof-specialty,Other-relative,White,Male,0,0,20,United-States,<=50K
77,67,?,212759,10th,6,Married-civ-spouse,?,Husband,White,Male,0,0,2,United-States,<=50K
81,52,Private,276515,Bachelors,13,Married-civ-spouse,Other-service,Husband,White,Male,0,0,40,Cuba,<=50K
83,59,Private,159937,HS-grad,9,Married-civ-spouse,Sales,Husband,White,Male,0,0,48,United-States,<=50K
85,53,Private,346253,HS-grad,9,Divorced,Sales,Own-child,White,Female,0,0,35,United-States,<=50K
90,57,Private,249977,Assoc-voc,11,Married-civ-spouse,Prof-specialty,Husband,White,Male,0,0,40,United-States,<=50K
100,76,Private,124191,Masters,14,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,40,United-States,>50K
112,56,Self-emp-not-inc,335605,HS-grad,9,Married-civ-spouse,Other-service,Husband,White,Male,0,1887,50,Canada,>50K
115,53,Private,95647,9th,5,Married-civ-spouse,Handlers-cleaners,Husband,White,Male,0,0,50,United-States,<=50K
116,56,Self-emp-inc,303090,Some-college,10,Married-civ-spouse,Sales,Husband,White,Male,0,0,50,United-States,<=50K
118,55,Private,247552,Some-college,10,Married-civ-spouse,Sales,Husband,White,Male,0,0,56,United-States,<=50K
140,61,Self-emp-inc,66614,HS-grad,9,Married-civ-spouse,Craft-repair,Husband,White,Male,0,0,40,United-States,<=50K
144,70,Private,105376,Some-college,10,Never-married,Tech-support,Other-relative,White,Male,0,0,40,United-States,<=50K
148,64,Private,181232,11th,7,Married-civ-spouse,Craft-repair,Husband,White,Male,0,2179,40,United-States,<=50K
154,52,?,252903,HS-grad,9,Divorced,?,Not-in-family,White,Male,0,0,45,United-States,>50K
157,71,Self-emp-not-inc,494223,Some-college,10,Separated,Sales,Unmarried,Black,Male,0,1816,2,United-States,<=50K
160,68,?,38317,1st-4th,2,Divorced,?,Not-in-family,White,Female,0,0,20,United-States,<=50K
169,66,Local-gov,54826,Assoc-voc,11,Widowed,Prof-specialty,Not-in-family,White,Female,0,0,20,United-States,<=50K
172,51,Private,96062,Some-college,10,Married-civ-spouse,Sales,Husband,White,Male,0,1977,40,United-States,>50K
187,53,?,135105,Bachelors,13,Divorced,?,Not-in-family,White,Female,0,0,50,United-States,<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32441,53,Private,304504,Some-college,10,Married-civ-spouse,Transport-moving,Husband,White,Male,0,1887,45,United-States,>50K
32444,51,Private,101432,HS-grad,9,Married-civ-spouse,Craft-repair,Husband,White,Male,0,0,40,United-States,<=50K
32445,61,Private,190682,HS-grad,9,Widowed,Craft-repair,Not-in-family,Black,Female,0,1669,50,United-States,<=50K
32446,53,Private,158993,HS-grad,9,Widowed,Machine-op-inspct,Unmarried,Black,Female,0,0,38,United-States,<=50K
32448,61,Private,137554,7th-8th,4,Married-civ-spouse,Craft-repair,Husband,White,Male,0,0,40,United-States,<=50K
32459,85,Private,98611,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,3,Poland,<=50K
32460,62,Private,128092,HS-grad,9,Widowed,Adm-clerical,Not-in-family,White,Female,0,0,32,United-States,<=50K
32463,58,Local-gov,223214,HS-grad,9,Married-civ-spouse,Other-service,Husband,White,Male,0,0,40,United-States,<=50K
32465,66,Private,269665,HS-grad,9,Widowed,Exec-managerial,Not-in-family,White,Female,0,0,25,United-States,<=50K
32467,55,Private,199713,9th,5,Married-civ-spouse,Craft-repair,Husband,White,Male,0,0,48,United-States,<=50K
32469,58,Self-emp-inc,181974,Doctorate,16,Never-married,Prof-specialty,Not-in-family,White,Female,0,0,99,?,<=50K
32479,64,State-gov,222966,7th-8th,4,Married-civ-spouse,Other-service,Wife,Black,Female,0,0,40,United-States,<=50K
32481,52,Private,301229,Assoc-voc,11,Separated,Sales,Unmarried,White,Female,0,0,40,United-States,<=50K
32487,51,Private,177669,Some-college,10,Married-civ-spouse,Sales,Husband,White,Male,0,0,60,United-States,<=50K
32489,61,Private,355645,HS-grad,9,Married-civ-spouse,Sales,Husband,Black,Male,0,0,40,United-States,<=50K
32490,60,?,134152,9th,5,Divorced,?,Not-in-family,Black,Male,0,0,35,United-States,<=50K
32494,82,?,403910,HS-grad,9,Never-married,?,Not-in-family,White,Male,0,0,3,United-States,<=50K
32498,57,Private,153918,HS-grad,9,Married-civ-spouse,Transport-moving,Husband,White,Male,0,0,40,United-States,<=50K
32501,71,Private,138145,9th,5,Married-civ-spouse,Other-service,Husband,White,Male,0,0,40,United-States,<=50K
32515,66,Federal-gov,47358,10th,6,Married-civ-spouse,Craft-repair,Husband,White,Male,3471,0,40,United-States,<=50K
32518,57,Local-gov,110417,HS-grad,9,Married-civ-spouse,Craft-repair,Husband,White,Male,99999,0,40,United-States,>50K
32522,58,Private,147707,11th,7,Married-civ-spouse,Sales,Husband,White,Male,0,0,40,United-States,<=50K
32525,81,?,120478,Assoc-voc,11,Divorced,?,Unmarried,White,Female,0,0,1,?,<=50K
32533,54,Private,337992,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,Asian-Pac-Islander,Male,0,0,50,Japan,>50K
32539,71,?,287372,Doctorate,16,Married-civ-spouse,?,Husband,White,Male,0,0,10,United-States,>50K
32542,72,?,129912,HS-grad,9,Married-civ-spouse,?,Husband,White,Male,0,0,25,United-States,<=50K
32548,65,Self-emp-not-inc,99359,Prof-school,15,Never-married,Prof-specialty,Not-in-family,White,Male,1086,0,60,United-States,<=50K
32554,53,Private,321865,Masters,14,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,40,United-States,>50K
32558,58,Private,151910,HS-grad,9,Widowed,Adm-clerical,Unmarried,White,Female,0,0,40,United-States,<=50K
32560,52,Self-emp-inc,287927,HS-grad,9,Married-civ-spouse,Exec-managerial,Wife,White,Female,15024,0,40,United-States,>50K

In [27]:
df["hours_per_month"] = df["hours-per-week"]*4

In [29]:
print(df["hours_per_month"])

0        160
1         52
2        160
3        160
4        160
5        160
6         64
7        180
8        200
9        160
10       320
11       160
12       120
13       200
14       160
15       180
16       140
17       160
18       200
19       180
20       240
21        80
22       160
23       160
24       160
25       160
26       160
27       240
28       320
29       160
        ...
32531    396
32532    240
32533    200
32534    156
32535    140
32536    220
32537    184
32538    180
32539     40
32540    160
32541    128
32542    100
32543    192
32544    120
32545     80
32546    160
32547    160
32548    240
32549    160
32550    200
32551    160
32552    180
32553     44
32554    160
32555    160
32556    152
32557    160
32558    160
32559     80
32560    160
Name: hours_per_month, Length: 32561, dtype: int64

In [30]:
# Per suddividere i dati in gruppi
groups_sex = df.groupby("sex")

In [31]:
groups_sex.groups

{' Female': Int64Index([    4,     5,     6,     8,    12,    19,    21,    24,    37,
                43,
             ...
             32540, 32541, 32543, 32544, 32545, 32546, 32549, 32556, 32558,
             32560],
            dtype='int64', length=10771),
 ' Male': Int64Index([    0,     1,     2,     3,     7,     9,    10,    11,    13,
                14,
             ...
             32547, 32548, 32550, 32551, 32552, 32553, 32554, 32555, 32557,
             32559],
            dtype='int64', length=21790)}

In [32]:
groups_race = df.groupby("race")

In [33]:
groups_race.groups

{' Amer-Indian-Eskimo': Int64Index([   15,   212,   226,   447,   516,   565,   596,   607,   903,
               940,
             ...
             30997, 31087, 31358, 31915, 32008, 32231, 32242, 32249, 32425,
             32551],
            dtype='int64', length=311),
 ' Asian-Pac-Islander': Int64Index([   11,    14,    27,    93,   139,   152,   162,   163,   213,
               255,
             ...
             32327, 32337, 32370, 32376, 32428, 32457, 32486, 32531, 32533,
             32553],
            dtype='int64', length=1039),
 ' Black': Int64Index([    3,     4,     6,    10,    13,    21,    22,    31,    34,
                45,
             ...
             32499, 32505, 32508, 32511, 32514, 32521, 32535, 32537, 32538,
             32541],
            dtype='int64', length=3124),
 ' Other': Int64Index([   50,   233,   356,   404,   530,   784,  1344,  1624,  1900,
              2452,
             ...
             31641, 31831, 31873, 31985, 32021, 32075, 32232, 32263, 32432,
             32544],
            dtype='int64', length=271),
 ' White': Int64Index([    0,     1,     2,     5,     7,     8,     9,    12,    16,
                17,
             ...
             32549, 32550, 32552, 32554, 32555, 32556, 32557, 32558, 32559,
             32560],
            dtype='int64', length=27816)}

In [34]:
groups_race.describe()

                         age                                                \
                       count       mean        std   min   25%   50%   75%
race
 Amer-Indian-Eskimo    311.0  37.173633  12.447130  17.0  28.0  35.0  45.5
 Asian-Pac-Islander   1039.0  37.746872  12.825133  17.0  28.0  36.0  45.0
 Black                3124.0  37.767926  12.759290  17.0  28.0  36.0  46.0
 Other                 271.0  33.457565  11.538865  17.0  25.0  31.0  41.0
 White               27816.0  38.769881  13.782306  17.0  28.0  37.0  48.0

                          capital-gain               ...   hours-per-week  \
                      max        count         mean  ...              75%
race                                                 ...
 Amer-Indian-Eskimo  82.0        311.0   625.266881  ...             40.0
 Asian-Pac-Islander  90.0       1039.0  1478.358037  ...             40.0
 Black               90.0       3124.0   609.940461  ...             40.0
 Other               77.0        271.0   934.660517  ...             40.0
 White               90.0      27816.0  1121.660375  ...             45.0

                          hours_per_month                                      \
                      max           count        mean        std   min    25%
race
 Amer-Indian-Eskimo  84.0           311.0  160.192926  46.781456  12.0  160.0
 Asian-Pac-Islander  99.0          1039.0  160.508181  50.227265   4.0  160.0
 Black               99.0          3124.0  153.691421  41.262584   4.0  148.0
 Other               98.0           271.0  157.874539  44.575019  20.0  144.0
 White               99.0         27816.0  162.756399  50.179183   4.0  160.0


                       50%    75%    max
race
 Amer-Indian-Eskimo  160.0  160.0  336.0
 Asian-Pac-Islander  160.0  160.0  396.0
 Black               160.0  160.0  396.0
 Other               160.0  160.0  392.0
 White               160.0  180.0  396.0

[5 rows x 56 columns]

In [35]:
# Per creare una variabile dummy (assume 1 o 0 se è soddisfatta o meno una condizione... )
df_dummy = pd.get_dummies(df["sex"], prefix = "Sex")

In [37]:
print(df_dummy.head(10))

   Sex_ Female  Sex_ Male
0            0          1
1            0          1
2            0          1
3            0          1
4            1          0
5            1          0
6            1          0
7            0          1
8            1          0
9            0          1

In [38]:
# Per cancellare una colonna
# del df["salary"]

#Per visualizzare dati duplicati
df.duplicated()

0        False
1        False
2        False
3        False
4        False
5        False
6        False
7        False
8        False
9        False
10       False
11       False
12       False
13       False
14       False
15       False
16       False
17       False
18       False
19       False
20       False
21       False
22       False
23       False
24       False
25       False
26       False
27       False
28       False
29       False
         ...
32531    False
32532    False
32533    False
32534    False
32535    False
32536    False
32537    False
32538    False
32539    False
32540    False
32541    False
32542    False
32543    False
32544    False
32545    False
32546    False
32547    False
32548    False
32549    False
32550    False
32551    False
32552    False
32553    False
32554    False
32555    False
32556    False
32557    False
32558    False
32559    False
32560    False
Length: 32561, dtype: bool

In [39]:
df2 = df.drop_duplicates()

In [41]:
# Si può notare come ci sia differenza tra il numero di casi di df (32561) e quelli di df2(32537)
df2.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 32537 entries, 0 to 32560
Data columns (total 16 columns):
age                32537 non-null int64
workclass          32537 non-null object
fnlwgt             32537 non-null int64
education          32537 non-null object
education-num      32537 non-null int64
marital-status     32537 non-null object
occupation         32537 non-null object
relationship       32537 non-null object
race               32537 non-null object
sex                32537 non-null object
capital-gain       32537 non-null int64
capital-loss       32537 non-null int64
hours-per-week     32537 non-null int64
native-country     32537 non-null object
salary             32537 non-null object
hours_per_month    32537 non-null int64
dtypes: int64(7), object(9)
memory usage: 4.2+ MB

In [42]:
# Per visualizzare i dati in modo longitudinale
df.stack()

0      age                                 39
       workclass                    State-gov
       fnlwgt                           77516
       education                    Bachelors
       education-num                       13
       marital-status           Never-married
       occupation                Adm-clerical
       relationship             Not-in-family
       race                             White
       sex                               Male
       capital-gain                      2174
       capital-loss                         0
       hours-per-week                      40
       native-country           United-States
       salary                           <=50K
       hours_per_month                    160
1      age                                 50
       workclass             Self-emp-not-inc
       fnlwgt                           83311
       education                    Bachelors
       education-num                       13
       marital-status      Married-civ-spouse
       occupation             Exec-managerial
       relationship                   Husband
       race                             White
       sex                               Male
       capital-gain                         0
       capital-loss                         0
       hours-per-week                      13
       native-country           United-States
                                 ...
32559  fnlwgt                          201490
       education                      HS-grad
       education-num                        9
       marital-status           Never-married
       occupation                Adm-clerical
       relationship                 Own-child
       race                             White
       sex                               Male
       capital-gain                         0
       capital-loss                         0
       hours-per-week                      20
       native-country           United-States
       salary                           <=50K
       hours_per_month                     80
32560  age                                 52
       workclass                 Self-emp-inc
       fnlwgt                          287927
       education                      HS-grad
       education-num                        9
       marital-status      Married-civ-spouse
       occupation             Exec-managerial
       relationship                      Wife
       race                             White
       sex                             Female
       capital-gain                     15024
       capital-loss                         0
       hours-per-week                      40
       native-country           United-States
       salary                            >50K
       hours_per_month                    160
Length: 520976, dtype: object

In [43]:
# Per estrarre dati in modo casuale...
df.sample(10)

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,salary,hours_per_month
1486,30,Private,57651,HS-grad,9,Never-married,Adm-clerical,Unmarried,White,Male,0,2001,42,United-States,<=50K,168
11994,40,Private,92717,HS-grad,9,Never-married,Other-service,Unmarried,Black,Female,0,0,40,United-States,<=50K,160
18730,65,?,315728,HS-grad,9,Widowed,?,Unmarried,White,Female,2329,0,75,United-States,<=50K,300
13345,33,Private,117779,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Wife,White,Female,0,0,46,United-States,>50K,184
20897,33,Self-emp-not-inc,93930,HS-grad,9,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,40,United-States,<=50K,160
9602,55,Private,234125,HS-grad,9,Married-civ-spouse,Other-service,Husband,White,Male,0,0,40,United-States,<=50K,160
23767,33,Private,618191,HS-grad,9,Never-married,Exec-managerial,Not-in-family,White,Female,0,0,40,United-States,<=50K,160
13722,45,Private,225456,Bachelors,13,Married-civ-spouse,Prof-specialty,Husband,White,Male,0,1977,40,United-States,>50K,160
12505,42,Private,160893,Some-college,10,Married-civ-spouse,Other-service,Wife,White,Female,0,0,23,United-States,<=50K,92
4617,32,Federal-gov,72338,Assoc-voc,11,Never-married,Prof-specialty,Other-relative,Asian-Pac-Islander,Male,0,0,40,United-States,<=50K,160

In [45]:
pd.isnull(df)

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,salary,hours_per_month
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
5,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
6,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
7,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
8,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
9,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
10,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
11,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
12,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
13,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
14,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
15,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
16,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
17,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
18,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
19,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
20,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
21,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
22,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
23,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
24,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
25,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
26,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
27,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
28,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
29,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32531,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
32532,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
32533,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
32534,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
32535,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
32536,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
32537,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
32538,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
32539,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
32540,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
32541,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
32542,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
32543,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
32544,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
32545,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
32546,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
32547,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
32548,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
32549,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
32550,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
32551,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
32552,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
32553,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
32554,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
32555,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
32556,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
32557,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
32558,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
32559,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
32560,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [46]:
# Per cancellare i valori mancanti
df.dropna()

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,salary,hours_per_month
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K,160
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K,52
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K,160
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K,160
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K,160
5,37,Private,284582,Masters,14,Married-civ-spouse,Exec-managerial,Wife,White,Female,0,0,40,United-States,<=50K,160
6,49,Private,160187,9th,5,Married-spouse-absent,Other-service,Not-in-family,Black,Female,0,0,16,Jamaica,<=50K,64
7,52,Self-emp-not-inc,209642,HS-grad,9,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,45,United-States,>50K,180
8,31,Private,45781,Masters,14,Never-married,Prof-specialty,Not-in-family,White,Female,14084,0,50,United-States,>50K,200
9,42,Private,159449,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,5178,0,40,United-States,>50K,160
10,37,Private,280464,Some-college,10,Married-civ-spouse,Exec-managerial,Husband,Black,Male,0,0,80,United-States,>50K,320
11,30,State-gov,141297,Bachelors,13,Married-civ-spouse,Prof-specialty,Husband,Asian-Pac-Islander,Male,0,0,40,India,>50K,160
12,23,Private,122272,Bachelors,13,Never-married,Adm-clerical,Own-child,White,Female,0,0,30,United-States,<=50K,120
13,32,Private,205019,Assoc-acdm,12,Never-married,Sales,Not-in-family,Black,Male,0,0,50,United-States,<=50K,200
14,40,Private,121772,Assoc-voc,11,Married-civ-spouse,Craft-repair,Husband,Asian-Pac-Islander,Male,0,0,40,?,>50K,160
15,34,Private,245487,7th-8th,4,Married-civ-spouse,Transport-moving,Husband,Amer-Indian-Eskimo,Male,0,0,45,Mexico,<=50K,180
16,25,Self-emp-not-inc,176756,HS-grad,9,Never-married,Farming-fishing,Own-child,White,Male,0,0,35,United-States,<=50K,140
17,32,Private,186824,HS-grad,9,Never-married,Machine-op-inspct,Unmarried,White,Male,0,0,40,United-States,<=50K,160
18,38,Private,28887,11th,7,Married-civ-spouse,Sales,Husband,White,Male,0,0,50,United-States,<=50K,200
19,43,Self-emp-not-inc,292175,Masters,14,Divorced,Exec-managerial,Unmarried,White,Female,0,0,45,United-States,>50K,180
20,40,Private,193524,Doctorate,16,Married-civ-spouse,Prof-specialty,Husband,White,Male,0,0,60,United-States,>50K,240
21,54,Private,302146,HS-grad,9,Separated,Other-service,Unmarried,Black,Female,0,0,20,United-States,<=50K,80
22,35,Federal-gov,76845,9th,5,Married-civ-spouse,Farming-fishing,Husband,Black,Male,0,0,40,United-States,<=50K,160
23,43,Private,117037,11th,7,Married-civ-spouse,Transport-moving,Husband,White,Male,0,2042,40,United-States,<=50K,160
24,59,Private,109015,HS-grad,9,Divorced,Tech-support,Unmarried,White,Female,0,0,40,United-States,<=50K,160
25,56,Local-gov,216851,Bachelors,13,Married-civ-spouse,Tech-support,Husband,White,Male,0,0,40,United-States,>50K,160
26,19,Private,168294,HS-grad,9,Never-married,Craft-repair,Own-child,White,Male,0,0,40,United-States,<=50K,160
27,54,?,180211,Some-college,10,Married-civ-spouse,?,Husband,Asian-Pac-Islander,Male,0,0,60,South,>50K,240
28,39,Private,367260,HS-grad,9,Divorced,Exec-managerial,Not-in-family,White,Male,0,0,80,United-States,<=50K,320
29,49,Private,193366,HS-grad,9,Married-civ-spouse,Craft-repair,Husband,White,Male,0,0,40,United-States,<=50K,160
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32531,30,?,33811,Bachelors,13,Never-married,?,Not-in-family,Asian-Pac-Islander,Female,0,0,99,United-States,<=50K,396
32532,34,Private,204461,Doctorate,16,Married-civ-spouse,Prof-specialty,Husband,White,Male,0,0,60,United-States,>50K,240
32533,54,Private,337992,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,Asian-Pac-Islander,Male,0,0,50,Japan,>50K,200
32534,37,Private,179137,Some-college,10,Divorced,Adm-clerical,Unmarried,White,Female,0,0,39,United-States,<=50K,156
32535,22,Private,325033,12th,8,Never-married,Protective-serv,Own-child,Black,Male,0,0,35,United-States,<=50K,140
32536,34,Private,160216,Bachelors,13,Never-married,Exec-managerial,Not-in-family,White,Female,0,0,55,United-States,>50K,220
32537,30,Private,345898,HS-grad,9,Never-married,Craft-repair,Not-in-family,Black,Male,0,0,46,United-States,<=50K,184
32538,38,Private,139180,Bachelors,13,Divorced,Prof-specialty,Unmarried,Black,Female,15020,0,45,United-States,>50K,180
32539,71,?,287372,Doctorate,16,Married-civ-spouse,?,Husband,White,Male,0,0,10,United-States,>50K,40
32540,45,State-gov,252208,HS-grad,9,Separated,Adm-clerical,Own-child,White,Female,0,0,40,United-States,<=50K,160
32541,41,?,202822,HS-grad,9,Separated,?,Not-in-family,Black,Female,0,0,32,United-States,<=50K,128
32542,72,?,129912,HS-grad,9,Married-civ-spouse,?,Husband,White,Male,0,0,25,United-States,<=50K,100
32543,45,Local-gov,119199,Assoc-acdm,12,Divorced,Prof-specialty,Unmarried,White,Female,0,0,48,United-States,<=50K,192
32544,31,Private,199655,Masters,14,Divorced,Other-service,Not-in-family,Other,Female,0,0,30,United-States,<=50K,120
32545,39,Local-gov,111499,Assoc-acdm,12,Married-civ-spouse,Adm-clerical,Wife,White,Female,0,0,20,United-States,>50K,80
32546,37,Private,198216,Assoc-acdm,12,Divorced,Tech-support,Not-in-family,White,Female,0,0,40,United-States,<=50K,160
32547,43,Private,260761,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,40,Mexico,<=50K,160
32548,65,Self-emp-not-inc,99359,Prof-school,15,Never-married,Prof-specialty,Not-in-family,White,Male,1086,0,60,United-States,<=50K,240
32549,43,State-gov,255835,Some-college,10,Divorced,Adm-clerical,Other-relative,White,Female,0,0,40,United-States,<=50K,160
32550,43,Self-emp-not-inc,27242,Some-college,10,Married-civ-spouse,Craft-repair,Husband,White,Male,0,0,50,United-States,<=50K,200
32551,32,Private,34066,10th,6,Married-civ-spouse,Handlers-cleaners,Husband,Amer-Indian-Eskimo,Male,0,0,40,United-States,<=50K,160
32552,43,Private,84661,Assoc-voc,11,Married-civ-spouse,Sales,Husband,White,Male,0,0,45,United-States,<=50K,180
32553,32,Private,116138,Masters,14,Never-married,Tech-support,Not-in-family,Asian-Pac-Islander,Male,0,0,11,Taiwan,<=50K,44
32554,53,Private,321865,Masters,14,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,40,United-States,>50K,160
32555,22,Private,310152,Some-college,10,Never-married,Protective-serv,Not-in-family,White,Male,0,0,40,United-States,<=50K,160
32556,27,Private,257302,Assoc-acdm,12,Married-civ-spouse,Tech-support,Wife,White,Female,0,0,38,United-States,<=50K,152
32557,40,Private,154374,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,40,United-States,>50K,160
32558,58,Private,151910,HS-grad,9,Widowed,Adm-clerical,Unmarried,White,Female,0,0,40,United-States,<=50K,160
32559,22,Private,201490,HS-grad,9,Never-married,Adm-clerical,Own-child,White,Male,0,0,20,United-States,<=50K,80
32560,52,Self-emp-inc,287927,HS-grad,9,Married-civ-spouse,Exec-managerial,Wife,White,Female,15024,0,40,United-States,>50K,160

In [48]:
# Per sostituire i dati mancanti
df['occupation'].fillna('Not specified')

0              Adm-clerical
1           Exec-managerial
2         Handlers-cleaners
3         Handlers-cleaners
4            Prof-specialty
5           Exec-managerial
6             Other-service
7           Exec-managerial
8            Prof-specialty
9           Exec-managerial
10          Exec-managerial
11           Prof-specialty
12             Adm-clerical
13                    Sales
14             Craft-repair
15         Transport-moving
16          Farming-fishing
17        Machine-op-inspct
18                    Sales
19          Exec-managerial
20           Prof-specialty
21            Other-service
22          Farming-fishing
23         Transport-moving
24             Tech-support
25             Tech-support
26             Craft-repair
27                        ?
28          Exec-managerial
29             Craft-repair
                ...
32531                     ?
32532        Prof-specialty
32533       Exec-managerial
32534          Adm-clerical
32535       Protective-serv
32536       Exec-managerial
32537          Craft-repair
32538        Prof-specialty
32539                     ?
32540          Adm-clerical
32541                     ?
32542                     ?
32543        Prof-specialty
32544         Other-service
32545          Adm-clerical
32546          Tech-support
32547     Machine-op-inspct
32548        Prof-specialty
32549          Adm-clerical
32550          Craft-repair
32551     Handlers-cleaners
32552                 Sales
32553          Tech-support
32554       Exec-managerial
32555       Protective-serv
32556          Tech-support
32557     Machine-op-inspct
32558          Adm-clerical
32559          Adm-clerical
32560       Exec-managerial
Name: occupation, Length: 32561, dtype: object